### ISSUE TITLE
[Bug] Error while deploying

### ISSUE THREAD

**Issue by Mevq1hgs** [TeamDaisyX/DaisyXMusic#112]
2021-09-27T07:53:00.426552+00:00 app[worker.1]: File "/app/DaisyXMusic/modules/channelplay.py", **line 235**
2021-09-27T07:53:00.426553+00:00 app[worker.1]: await cb.message.edit(updated_stats(conv, qeue), reply_markup=r_ply("play"))
2021-09-27T07:53:00.426563+00:00 app[worker.1]: IndentationError: unexpected indent

**Comment by Hunter-XDD** [comment]
now fixed just try

**Comment by Mevq1hgs** [comment]
> now fixed just try

[Not Fixed]

2021-09-27T13:14:45.635276+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-27T13:14:45.635302+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2021-09-27T13:14:45.635396+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-09-27T13:14:45.635404+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2021-09-27T13:14:45.635475+00:00 app[worker.1]:     exec(code, run_globals)
2021-09-27T13:14:45.635479+00:00 app[worker.1]:   File "/app/DaisyXMusic/__main__.py", line 37, in <module>
2021-09-27T13:14:45.635540+00:00 app[worker.1]:     bot.start()
2021-09-27T13:14:45.635548+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-09-27T13:14:45.635607+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-09-27T13:14:45.635612+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-09-27T13:14:45.635784+00:00 app[worker.1]:     return future.result()
2021-09-27T13:14:45.635786+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2021-09-27T13:14:45.635854+00:00 app[worker.1]:     await self.initialize()
2021-09-27T13:14:45.635856+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2021-09-27T13:14:45.635916+00:00 app[worker.1]:     self.load_plugins()
2021-09-27T13:14:45.635923+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 715, in load_plugins
2021-09-27T13:14:45.636104+00:00 app[worker.1]:     module = import_module(module_path)
2021-09-27T13:14:45.636111+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-09-27T13:14:45.636179+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-09-27T13:14:45.636181+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-09-27T13:14:45.636271+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-09-27T13:14:45.636303+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-09-27T13:14:45.636335+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-09-27T13:14:45.636368+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 846, in exec_module
2021-09-27T13:14:45.636416+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 983, in get_code
2021-09-27T13:14:45.636449+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
2021-09-27T13:14:45.636481+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-09-27T13:14:45.636521+00:00 app[worker.1]:   File "/app/DaisyXMusic/modules/channelplay.py", line 235
2021-09-27T13:14:45.636523+00:00 app[worker.1]:     await cb.message.edit(updated_stats(conv, qeue), reply_markup=r_ply("play"))
2021-09-27T13:14:45.636533+00:00 app[worker.1]: IndentationError: unexpected indent
2021-09-27T13:14:45.636682+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-09-27T13:14:45.636682+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-09-27T13:14:45.636682+00:00 app[worker.1]:
