### ISSUE TITLE
[Bug] [Not Fixed] Error while deploying

### ISSUE THREAD

**Issue by Mevq1hgs** [TeamDaisyX/DaisyXMusic#113]
2021-09-27T15:02:17.326774+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-27T15:02:17.326789+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2021-09-27T15:02:17.326926+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-09-27T15:02:17.326934+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2021-09-27T15:02:17.327015+00:00 app[worker.1]:     exec(code, run_globals)
2021-09-27T15:02:17.327016+00:00 app[worker.1]:   File "/app/DaisyXMusic/__main__.py", line 37, in <module>
2021-09-27T15:02:17.327083+00:00 app[worker.1]:     bot.start()
2021-09-27T15:02:17.327085+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-09-27T15:02:17.327160+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-09-27T15:02:17.327162+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-09-27T15:02:17.327338+00:00 app[worker.1]:     return future.result()
2021-09-27T15:02:17.327339+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2021-09-27T15:02:17.327417+00:00 app[worker.1]:     await self.initialize()
2021-09-27T15:02:17.327419+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2021-09-27T15:02:17.327488+00:00 app[worker.1]:     self.load_plugins()
2021-09-27T15:02:17.327490+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 715, in load_plugins
2021-09-27T15:02:17.327681+00:00 app[worker.1]:     module = import_module(module_path)
2021-09-27T15:02:17.327683+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-09-27T15:02:17.327770+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-09-27T15:02:17.327772+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-09-27T15:02:17.327872+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-09-27T15:02:17.327910+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-09-27T15:02:17.327947+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-09-27T15:02:17.327985+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 846, in exec_module
2021-09-27T15:02:17.328046+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 983, in get_code
2021-09-27T15:02:17.328084+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
2021-09-27T15:02:17.328122+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-09-27T15:02:17.328168+00:00 app[worker.1]:   File "/app/DaisyXMusic/modules/channelplay.py", line 341
2021-09-27T15:02:17.328170+00:00 app[worker.1]:     elif type_ == "cmute":
2021-09-27T15:02:17.328178+00:00 app[worker.1]:     ^
2021-09-27T15:02:17.328185+00:00 app[worker.1]: SyntaxError: invalid syntax
2021-09-27T15:02:17.328375+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-09-27T15:02:17.328376+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-09-27T15:02:17.328376+00:00 app[worker.1]: 
2021-09-27T15:02:17.616804+00:00 heroku[worker.1]: Process exited with status 1
2021-09-27T15:02:17.662063+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by Mevq1hgs** [comment]
Fixed?
I redeployed and the same error is still there.

**Comment by Hunter-XDD** [comment]
ohh okay

**Comment by Mevq1hgs** [comment]
Fixed
