### ISSUE TITLE
[Bug] Errors

### ISSUE THREAD

**Issue by Mevq1hgs** [TeamDaisyX/DaisyXMusic#115]
Error while using cplay command:

ERROR:pyrogram.dispatcher:name 'toxt' is not defined
2021-10-01T12:21:07.407681+00:00 app[worker.1]: Traceback (most recent call last):
2021-10-01T12:21:07.407683+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-10-01T12:21:07.407683+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-10-01T12:21:07.407684+00:00 app[worker.1]:   File "/app/DaisyXMusic/helpers/decorators.py", line 40, in decorator
2021-10-01T12:21:07.407684+00:00 app[worker.1]:     return await func(client, message)
2021-10-01T12:21:07.407685+00:00 app[worker.1]:   File "/app/DaisyXMusic/modules/channelplay.py", line 477, in play
2021-10-01T12:21:07.407685+00:00 app[worker.1]:     query = toxt
2021-10-01T12:21:07.407685+00:00 app[worker.1]: NameError: name 'toxt' is not defined

Same command, different error:

2021-10-01T12:23:21.814296+00:00 app[worker.1]: ERROR:pyrogram.dispatcher:name 'os' is not defined
2021-10-01T12:23:21.814302+00:00 app[worker.1]: Traceback (most recent call last):
2021-10-01T12:23:21.814303+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-10-01T12:23:21.814303+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-10-01T12:23:21.814304+00:00 app[worker.1]:   File "/app/DaisyXMusic/helpers/decorators.py", line 40, in decorator
2021-10-01T12:23:21.814305+00:00 app[worker.1]:     return await func(client, message)
2021-10-01T12:23:21.814305+00:00 app[worker.1]:   File "/app/DaisyXMusic/modules/channelplay.py", line 618, in play
2021-10-01T12:23:21.814306+00:00 app[worker.1]:     os.remove("final.png")
2021-10-01T12:23:21.814306+00:00 app[worker.1]: NameError: name 'os' is not defined

Hope these will be resolved :)

**Comment by Mevq1hgs** [comment]
Fixed now :)
