### ISSUE TITLE
Bot Crashes Due To PyTgCalls Update

### ISSUE THREAD

**Issue by Nisarga-Developer** [TeamDaisyX/DaisyXMusic#80]
```
2021-08-11T15:11:19.398580+00:00 app[worker.1]: [93mUpdate Available!
2021-08-11T15:11:19.398581+00:00 app[worker.1]: New PyTgCalls v0.6.1 is now available!
2021-08-11T15:11:19.398581+00:00 app[worker.1]: [0m
2021-08-11T15:11:19.531038+00:00 app[worker.1]: Starting on port: 24859
2021-08-11T15:11:19.725332+00:00 heroku[worker.1]: Process exited with status 0
2021-08-11T15:11:19.846004+00:00 heroku[worker.1]: State changed from up to crashed
```

How to fix this? These are heroku logs

**Comment by Nisarga-Developer** [comment]
```
2021-08-11T15:10:52.569403+00:00 app[worker.1]: Error in atexit._run_exitfuncs:
2021-08-11T15:10:52.569424+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-11T15:10:52.569425+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web.py", line 419, in run_app
2021-08-11T15:10:52.569801+00:00 app[worker.1]:     loop.run_until_complete(_run_app(app,
2021-08-11T15:10:52.569882+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-08-11T15:10:52.570201+00:00 app[worker.1]:     return future.result()
2021-08-11T15:10:52.570211+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web.py", line 359, in _run_app
2021-08-11T15:10:52.570483+00:00 app[worker.1]:     await site.start()
2021-08-11T15:10:52.570503+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 100, in start
2021-08-11T15:10:52.570651+00:00 app[worker.1]:     self._server = await loop.create_server(  # type: ignore
2021-08-11T15:10:52.570668+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1460, in create_server
2021-08-11T15:10:52.571224+00:00 app[worker.1]:     infos = await tasks.gather(*fs, loop=self)
2021-08-11T15:10:52.571245+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1400, in _create_server_getaddrinfo
2021-08-11T15:10:52.571815+00:00 app[worker.1]:     infos = await self._ensure_resolved((host, port), family=family,
2021-08-11T15:10:52.571844+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
2021-08-11T15:10:52.572353+00:00 app[worker.1]:     return await loop.getaddrinfo(host, port, family=family, type=type,
2021-08-11T15:10:52.572371+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
2021-08-11T15:10:52.572712+00:00 app[worker.1]:     return await self.run_in_executor(
2021-08-11T15:10:52.572722+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
2021-08-11T15:10:52.573058+00:00 app[worker.1]:     executor.submit(func, *args), loop=self)
2021-08-11T15:10:52.573070+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
2021-08-11T15:10:52.573209+00:00 app[worker.1]:     raise RuntimeError('cannot schedule new futures after '
2021-08-11T15:10:52.573226+00:00 app[worker.1]: RuntimeError: cannot schedule new futures after interpreter shutdown
2021-08-11T15:10:52.573330+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-08-11T15:10:52.573330+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-08-11T15:10:52.573331+00:00 app[worker.1]: 
2021-08-11T15:10:52.573331+00:00 app[worker.1]: PyTgCalls v0.6.0, Copyright (C) 2021 Laky-64 <https://github.com/Laky-64>
2021-08-11T15:10:52.573331+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-08-11T15:10:52.573332+00:00 app[worker.1]: 
2021-08-11T15:10:52.573332+00:00 app[worker.1]: [93mUpdate Available!
2021-08-11T15:10:52.573332+00:00 app[worker.1]: New PyTgCalls v0.6.1 is now available!
2021-08-11T15:10:52.573332+00:00 app[worker.1]: [0m
2021-08-11T15:10:52.673206+00:00 app[worker.1]: Starting on port: 24859
2021-08-11T15:11:07.106199+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ -m\ DaisyXMusic`
2021-08-11T15:11:07.952078+00:00 heroku[worker.1]: State changed from starting to up
2021-08-11T15:11:17.055998+00:00 app[worker.1]: [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
2021-08-11T15:11:17.056030+00:00 app[worker.1]: [debug] youtube-dl version 2021.06.06
2021-08-11T15:11:17.066184+00:00 app[worker.1]: [debug] Python version 3.9.6 (CPython) - Linux-4.4.0-1094-aws-x86_64-with-glibc2.28
2021-08-11T15:11:17.222177+00:00 app[worker.1]: [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
2021-08-11T15:11:17.229104+00:00 app[worker.1]: [debug] Proxy map: {}
2021-08-11T15:11:17.235921+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("_start") in group 0 from "DaisyXMusic.modules.private"
2021-08-11T15:11:17.235973+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("gstart") in group 0 from "DaisyXMusic.modules.private"
2021-08-11T15:11:17.236016+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("_help") in group 0 from "DaisyXMusic.modules.private"
2021-08-11T15:11:17.236066+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] CallbackQueryHandler("help_answer") in group 0 from "DaisyXMusic.modules.private"
2021-08-11T15:11:17.236102+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("ghelp") in group 0 from "DaisyXMusic.modules.private"
2021-08-11T15:11:17.240144+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("song") in group 0 from "DaisyXMusic.modules.song"
2021-08-11T15:11:17.240210+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("jssong") in group 0 from "DaisyXMusic.modules.song"
2021-08-11T15:11:17.240252+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("ytmusic") in group 0 from "DaisyXMusic.modules.song"
2021-08-11T15:11:17.241511+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("addchannel") in group 0 from "DaisyXMusic.modules.userbotjoin"
2021-08-11T15:11:17.241559+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("bye") in group 0 from "DaisyXMusic.modules.userbotjoin"
2021-08-11T15:11:17.241600+00:00 app[worker.1]: INFO:pyrogram.client:[:memory:] [LOAD] MessageHandler("addcchannel") in group 0 from "DaisyXMusic.modules.userbotjoin"
2021-08-11T15:11:19.395218+00:00 app[worker.1]: Error in atexit._run_exitfuncs:
2021-08-11T15:11:19.395299+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-11T15:11:19.395337+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web.py", line 419, in run_app
2021-08-11T15:11:19.395779+00:00 app[worker.1]:     loop.run_until_complete(_run_app(app,
2021-08-11T15:11:19.395812+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-08-11T15:11:19.396166+00:00 app[worker.1]:     return future.result()
2021-08-11T15:11:19.396193+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web.py", line 359, in _run_app
2021-08-11T15:11:19.396483+00:00 app[worker.1]:     await site.start()
2021-08-11T15:11:19.396510+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 100, in start
2021-08-11T15:11:19.396706+00:00 app[worker.1]:     self._server = await loop.create_server(  # type: ignore
2021-08-11T15:11:19.396731+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1460, in create_server
2021-08-11T15:11:19.397232+00:00 app[worker.1]:     infos = await tasks.gather(*fs, loop=self)
2021-08-11T15:11:19.397237+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1400, in _create_server_getaddrinfo
2021-08-11T15:11:19.397579+00:00 app[worker.1]:     infos = await self._ensure_resolved((host, port), family=family,
2021-08-11T15:11:19.397581+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
2021-08-11T15:11:19.397893+00:00 app[worker.1]:     return await loop.getaddrinfo(host, port, family=family, type=type,
2021-08-11T15:11:19.397895+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
2021-08-11T15:11:19.398109+00:00 app[worker.1]:     return await self.run_in_executor(
2021-08-11T15:11:19.398111+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
2021-08-11T15:11:19.398359+00:00 app[worker.1]:     executor.submit(func, *args), loop=self)
2021-08-11T15:11:19.398361+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
2021-08-11T15:11:19.398463+00:00 app[worker.1]:     raise RuntimeError('cannot schedule new futures after '
2021-08-11T15:11:19.398482+00:00 app[worker.1]: RuntimeError: cannot schedule new futures after interpreter shutdown
2021-08-11T15:11:19.398577+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-08-11T15:11:19.398577+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-08-11T15:11:19.398579+00:00 app[worker.1]: 
2021-08-11T15:11:19.398579+00:00 app[worker.1]: PyTgCalls v0.6.0, Copyright (C) 2021 Laky-64 <https://github.com/Laky-64>
2021-08-11T15:11:19.398579+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-08-11T15:11:19.398580+00:00 app[worker.1]: 
2021-08-11T15:11:19.398580+00:00 app[worker.1]: [93mUpdate Available!
2021-08-11T15:11:19.398581+00:00 app[worker.1]: New PyTgCalls v0.6.1 is now available!
2021-08-11T15:11:19.398581+00:00 app[worker.1]: [0m
2021-08-11T15:11:19.531038+00:00 app[worker.1]: Starting on port: 24859
2021-08-11T15:11:19.725332+00:00 heroku[worker.1]: Process exited with status 0
2021-08-11T15:11:19.846004+00:00 heroku[worker.1]: State changed from up to crashed 
```  (I also got these)

**Comment by realme417** [comment]
### **yes vro you spoken truth**

**Comment by InukaAsith** [comment]
> ```
> 2021-08-11T15:11:19.398580+00:00 app[worker.1]: �[93mUpdate Available!
> 2021-08-11T15:11:19.398581+00:00 app[worker.1]: New PyTgCalls v0.6.1 is now available!
> 2021-08-11T15:11:19.398581+00:00 app[worker.1]: �[0m
> 2021-08-11T15:11:19.531038+00:00 app[worker.1]: Starting on port: 24859
> 2021-08-11T15:11:19.725332+00:00 heroku[worker.1]: Process exited with status 0
> 2021-08-11T15:11:19.846004+00:00 heroku[worker.1]: State changed from up to crashed
> ```
> 
> How to fix this? These are heroku logs

Fork repo
in requirements.txt change
py-tgcalls

to

py-tgcalls==0.5.5

**Comment by InukaAsith** [comment]
We are testing latest version of pytgcalls now
We will rollback if latest version not working
